# Generated by Django 6.0.3 on 2026-03-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
